import Foundation

/// Carpetas regenerables dentro de proyectos, además de las que ya reconoce el índice
/// (node_modules, build, Pods, .gradle, DerivedData, target…). Cada una exige un archivo que identifique el proyecto.
extension Catalogo {
    static let artefactosDeProyecto: [ReglaArtefacto] = [
        // Unity
        ReglaArtefacto(carpeta: "Library", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "caché de Unity",
                       consecuencia: "Unity la regenera al abrir el proyecto (la primera vez tarda bastante)."),
        ReglaArtefacto(carpeta: "Temp", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "temporales de Unity", consecuencia: "Unity los crea de nuevo."),
        ReglaArtefacto(carpeta: "Obj", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "compilación intermedia de Unity", consecuencia: "Unity la vuelve a generar."),
        ReglaArtefacto(carpeta: "Logs", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "registros de Unity", consecuencia: "Nada: solo son registros."),
        // Unreal Engine
        ReglaArtefacto(carpeta: "Intermediate", marcadores: ["*.uproject", "*.uplugin"],
                       descripcion: "compilación intermedia de Unreal",
                       consecuencia: "Unreal la regenera al abrir o compilar el proyecto."),
        ReglaArtefacto(carpeta: "DerivedDataCache", marcadores: ["*.uproject"],
                       descripcion: "caché de datos derivados de Unreal",
                       consecuencia: "Unreal vuelve a procesar los recursos al abrir el proyecto (tarda)."),
        ReglaArtefacto(carpeta: "Binaries", marcadores: ["*.uproject", "*.uplugin"],
                       descripcion: "binarios compilados de Unreal",
                       consecuencia: "Hay que volver a compilar el proyecto; en proyectos sin código C++ puede que no se puedan regenerar.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "Saved", marcadores: ["*.uproject"],
                       descripcion: "carpeta Saved de Unreal",
                       consecuencia: "Contiene registros y cachés, pero también autoguardados, capturas y ajustes del editor: revísala antes.",
                       riesgo: .revisar),
        // Godot
        ReglaArtefacto(carpeta: ".godot", marcadores: ["project.godot"],
                       descripcion: "caché de importación de Godot",
                       consecuencia: "Godot vuelve a importar los recursos al abrir el proyecto."),
        ReglaArtefacto(carpeta: ".import", marcadores: ["project.godot"],
                       descripcion: "caché de importación de Godot 3",
                       consecuencia: "Godot vuelve a importar los recursos al abrir el proyecto."),
        // .NET
        ReglaArtefacto(carpeta: "bin", marcadores: ["*.csproj", "*.fsproj", "*.vbproj"],
                       descripcion: "compilación de .NET", consecuencia: "Se vuelve a generar con «dotnet build»."),
        ReglaArtefacto(carpeta: "obj", marcadores: ["*.csproj", "*.fsproj", "*.vbproj"],
                       descripcion: "compilación intermedia de .NET", consecuencia: "Se vuelve a generar con «dotnet build»."),
        // C y C++
        ReglaArtefacto(carpeta: "cmake-build-*", marcadores: ["CMakeLists.txt"],
                       descripcion: "compilación de CLion/CMake", consecuencia: "CLion la vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: ".externalNativeBuild", marcadores: ["build.gradle", "build.gradle.kts"],
                       descripcion: "compilación nativa antigua de Android",
                       consecuencia: "Gradle la vuelve a generar si el proyecto todavía la usa."),
        // Terraform
        ReglaArtefacto(carpeta: ".terraform", marcadores: ["*.tf"],
                       descripcion: "proveedores y módulos de Terraform",
                       consecuencia: "Ejecuta «terraform init» antes de volver a usar el proyecto. Tu estado (terraform.tfstate) no se toca."),
        // Python
        ReglaArtefacto(carpeta: "__pycache__", marcadores: ["*.py"],
                       descripcion: "bytecode de Python", consecuencia: "Python lo vuelve a generar al ejecutar el código."),
        ReglaArtefacto(carpeta: ".pytest_cache", marcadores: ["pyproject.toml", "setup.py", "setup.cfg", "pytest.ini", "tox.ini", "*.py"],
                       descripcion: "caché de pytest", consecuencia: "Se regenera al ejecutar las pruebas."),
        ReglaArtefacto(carpeta: ".mypy_cache", marcadores: ["pyproject.toml", "setup.py", "setup.cfg", "mypy.ini", "*.py"],
                       descripcion: "caché de mypy", consecuencia: "mypy la regenera (la primera revisión irá más lenta)."),
        ReglaArtefacto(carpeta: ".ruff_cache", marcadores: ["pyproject.toml", "ruff.toml", ".ruff.toml", "*.py"],
                       descripcion: "caché de Ruff", consecuencia: "Ruff la regenera."),
        ReglaArtefacto(carpeta: ".tox", marcadores: ["tox.ini", "pyproject.toml", "setup.cfg"],
                       descripcion: "entornos de tox", consecuencia: "tox los vuelve a crear al ejecutar las pruebas."),
        ReglaArtefacto(carpeta: ".nox", marcadores: ["noxfile.py"],
                       descripcion: "entornos de nox", consecuencia: "nox los vuelve a crear."),
        ReglaArtefacto(carpeta: ".ipynb_checkpoints", marcadores: ["*.ipynb"],
                       descripcion: "puntos de control de Jupyter",
                       consecuencia: "Se pierden las versiones guardadas automáticamente de tus cuadernos; los cuadernos no se tocan.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "*.egg-info", marcadores: ["setup.py", "pyproject.toml", "setup.cfg"],
                       descripcion: "metadatos de paquete de Python", consecuencia: "Se regeneran al instalar el paquete."),
        ReglaArtefacto(carpeta: ".eggs", marcadores: ["setup.py"],
                       descripcion: "dependencias de setuptools", consecuencia: "Se vuelven a descargar al instalar."),
        ReglaArtefacto(carpeta: "dist", marcadores: ["pyproject.toml", "setup.py", "package.json"],
                       descripcion: "paquetes generados", consecuencia: "Se vuelven a generar al compilar o empaquetar.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "build", marcadores: ["pyproject.toml", "setup.py", "*.xcodeproj"],
                       descripcion: "compilación", consecuencia: "Se vuelve a generar al compilar.",
                       soloSiIgnoradaPorGit: true),
        // JavaScript
        ReglaArtefacto(carpeta: "out", marcadores: ["package.json", "*.iml"],
                       descripcion: "compilación", consecuencia: "Se vuelve a generar al compilar.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".output", marcadores: ["nuxt.config.ts", "nuxt.config.js"],
                       descripcion: "compilación de Nuxt", consecuencia: "Nuxt la vuelve a generar."),
        ReglaArtefacto(carpeta: "storybook-static", marcadores: ["package.json"],
                       descripcion: "Storybook compilado", consecuencia: "Se vuelve a generar con «build-storybook».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".docusaurus", marcadores: ["docusaurus.config.js", "docusaurus.config.ts"],
                       descripcion: "caché de Docusaurus", consecuencia: "Docusaurus la vuelve a generar."),
        ReglaArtefacto(carpeta: ".cache", marcadores: ["gatsby-config.js", "gatsby-config.ts"],
                       descripcion: "caché de Gatsby", consecuencia: "Gatsby la vuelve a generar."),
        ReglaArtefacto(carpeta: "public", marcadores: ["gatsby-config.js", "gatsby-config.ts"],
                       descripcion: "sitio compilado de Gatsby", consecuencia: "Gatsby lo vuelve a generar.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".nyc_output", marcadores: ["package.json"],
                       descripcion: "datos de cobertura de pruebas", consecuencia: "Se regeneran al ejecutar las pruebas."),
        ReglaArtefacto(carpeta: "coverage", marcadores: ["package.json"],
                       descripcion: "informe de cobertura de pruebas", consecuencia: "Se regenera al ejecutar las pruebas.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".astro", marcadores: ["astro.config.mjs", "astro.config.ts", "astro.config.js"],
                       descripcion: "caché de Astro", consecuencia: "Astro la vuelve a generar."),
        ReglaArtefacto(carpeta: ".wrangler", marcadores: ["wrangler.toml", "wrangler.json", "wrangler.jsonc"],
                       descripcion: "datos locales de Wrangler (Cloudflare)",
                       consecuencia: "Se pierden los datos de prueba locales (KV, D1) del modo desarrollo.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: ".serverless", marcadores: ["serverless.yml", "serverless.ts", "serverless.json"],
                       descripcion: "paquetes de Serverless", consecuencia: "Se vuelven a generar al desplegar."),
        ReglaArtefacto(carpeta: "cdk.out", marcadores: ["cdk.json"],
                       descripcion: "plantillas generadas por AWS CDK", consecuencia: "Se vuelven a generar con «cdk synth»."),
        ReglaArtefacto(carpeta: ".swc", marcadores: ["package.json"],
                       descripcion: "caché de SWC", consecuencia: "Se regenera al compilar."),
        // PHP
        ReglaArtefacto(carpeta: "vendor", marcadores: ["composer.json"],
                       descripcion: "dependencias de Composer", consecuencia: "Ejecuta «composer install» antes de volver a usar el proyecto."),
        // Elixir, Haskell, Zig, Scala, Elm
        ReglaArtefacto(carpeta: "_build", marcadores: ["mix.exs"],
                       descripcion: "compilación de Elixir", consecuencia: "Mix la vuelve a generar."),
        ReglaArtefacto(carpeta: "deps", marcadores: ["mix.exs"],
                       descripcion: "dependencias de Elixir", consecuencia: "Ejecuta «mix deps.get» antes de volver a usar el proyecto."),
        ReglaArtefacto(carpeta: ".stack-work", marcadores: ["stack.yaml"],
                       descripcion: "compilación de Stack (Haskell)", consecuencia: "Stack la vuelve a generar."),
        ReglaArtefacto(carpeta: "dist-newstyle", marcadores: ["cabal.project", "*.cabal"],
                       descripcion: "compilación de Cabal (Haskell)", consecuencia: "Cabal la vuelve a generar."),
        ReglaArtefacto(carpeta: "zig-cache", marcadores: ["build.zig"],
                       descripcion: "caché de Zig", consecuencia: "Zig la vuelve a generar."),
        ReglaArtefacto(carpeta: ".zig-cache", marcadores: ["build.zig"],
                       descripcion: "caché de Zig", consecuencia: "Zig la vuelve a generar."),
        ReglaArtefacto(carpeta: "zig-out", marcadores: ["build.zig"],
                       descripcion: "compilación de Zig", consecuencia: "Zig la vuelve a generar."),
        ReglaArtefacto(carpeta: ".bloop", marcadores: ["build.sbt", "build.sc"],
                       descripcion: "compilación de Bloop (Scala)", consecuencia: "Se regenera al importar el proyecto."),
        ReglaArtefacto(carpeta: ".metals", marcadores: ["build.sbt", "build.sc"],
                       descripcion: "índices de Metals (Scala)", consecuencia: "Metals los vuelve a generar."),
        ReglaArtefacto(carpeta: "target", marcadores: ["build.sbt"],
                       descripcion: "compilación de sbt", consecuencia: "sbt la vuelve a generar."),
        ReglaArtefacto(carpeta: "elm-stuff", marcadores: ["elm.json"],
                       descripcion: "compilación de Elm", consecuencia: "Elm la vuelve a generar."),
        // Sitios estáticos
        ReglaArtefacto(carpeta: "_site", marcadores: ["_config.yml"],
                       descripcion: "sitio compilado de Jekyll", consecuencia: "Jekyll lo vuelve a generar."),
        ReglaArtefacto(carpeta: ".jekyll-cache", marcadores: ["_config.yml"],
                       descripcion: "caché de Jekyll", consecuencia: "Jekyll la vuelve a generar."),
        ReglaArtefacto(carpeta: ".sass-cache", marcadores: ["_config.yml", "*.scss", "*.sass"],
                       descripcion: "caché de Sass", consecuencia: "Sass la vuelve a generar."),
        ReglaArtefacto(carpeta: "resources", marcadores: ["hugo.toml", "hugo.yaml", "hugo.json"],
                       descripcion: "recursos generados por Hugo", consecuencia: "Hugo los vuelve a generar.",
                       soloSiIgnoradaPorGit: true),
        // iOS
        ReglaArtefacto(carpeta: "Carthage", marcadores: ["Cartfile"],
                       descripcion: "dependencias de Carthage", consecuencia: "Ejecuta «carthage bootstrap» antes de volver a compilar."),
        // Otros
        ReglaArtefacto(carpeta: ".vagrant", marcadores: ["Vagrantfile"],
                       descripcion: "estado de la máquina de Vagrant",
                       consecuencia: "Vagrant perderá la referencia a la máquina virtual ya creada (no la borra): revísalo.",
                       riesgo: .revisar),
    ]
}
