import Foundation

/// Más carpetas regenerables dentro de proyectos (segunda tanda, verificada).
extension Catalogo {
    static let artefactosExtra: [ReglaArtefacto] = [
        ReglaArtefacto(carpeta: ".output", marcadores: ["wxt.config.ts", "wxt.config.js", "wxt.config.mjs"],
                       descripcion: "compilación y paquetes .zip de una extensión de navegador (WXT)",
                       consecuencia: "Se vuelve a generar con «wxt build» o «wxt zip». Si subiste alguno de esos .zip a una tienda, la tienda guarda su copia.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: ".wxt", marcadores: ["wxt.config.ts", "wxt.config.js", "wxt.config.mjs"],
                       descripcion: "tipos generados y caché de WXT (extensiones de navegador)",
                       consecuencia: "WXT lo regenera con «wxt prepare». Si guardaste ahí un perfil de Chrome de pruebas (.wxt/chrome-data), perderás sus inicios de sesión y extensiones.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: ".plasmo", marcadores: ["package.json"],
                       descripcion: "archivos generados y caché de Plasmo (extensiones de navegador)",
                       consecuencia: "Plasmo lo regenera en el próximo «plasmo dev» o «plasmo build»; tu código no se toca."),
        ReglaArtefacto(carpeta: "web-ext-artifacts", marcadores: ["manifest.json", "package.json"],
                       descripcion: "paquetes .zip/.xpi generados por web-ext (Firefox)",
                       consecuencia: "Se vuelven a generar con «web-ext build». Si subiste uno a la tienda de Mozilla, la tienda conserva su copia.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "playwright-report", marcadores: ["playwright.config.ts", "playwright.config.js", "playwright.config.mjs"],
                       descripcion: "informe HTML de pruebas de Playwright",
                       consecuencia: "Se vuelve a crear la próxima vez que ejecutes las pruebas; tu código no se toca."),
        ReglaArtefacto(carpeta: "test-results", marcadores: ["playwright.config.ts", "playwright.config.js", "playwright.config.mjs"],
                       descripcion: "trazas, capturas y vídeos de pruebas de Playwright",
                       consecuencia: "Playwright la vacía y la vuelve a llenar en cada ejecución.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "blob-report", marcadores: ["playwright.config.ts", "playwright.config.js", "playwright.config.mjs"],
                       descripcion: "informes parciales de Playwright al repartir pruebas (sharding)",
                       consecuencia: "Se vuelven a crear al ejecutar las pruebas.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".lighthouseci", marcadores: ["lighthouserc.js", ".lighthouserc.js", "lighthouserc.cjs", ".lighthouserc.cjs", "lighthouserc.json", ".lighthouserc.json", "lighthouserc.yml", ".lighthouserc.yml", "lighthouserc.yaml", ".lighthouserc.yaml", "package.json"],
                       descripcion: "informes guardados de Lighthouse CI",
                       consecuencia: "Se vuelven a generar con «lhci collect»; tu código no se toca."),
        ReglaArtefacto(carpeta: ".trash", marcadores: [".obsidian"],
                       descripcion: "papelera interna de una bóveda de Obsidian",
                       consecuencia: "Se borran las notas que ya eliminaste desde Obsidian (Obsidian no las muestra ni las sincroniza). Tus notas actuales no se tocan.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "SourcePackages", marcadores: ["*.xcodeproj", "*.xcworkspace"],
                       descripcion: "paquetes de Swift descargados por xcodebuild",
                       consecuencia: "Xcode los vuelve a descargar al resolver los paquetes (necesita internet).",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "*.xcresult", marcadores: ["*.xcodeproj", "*.xcworkspace", "Package.swift"],
                       descripcion: "resultados de pruebas de Xcode",
                       consecuencia: "Pierdes el informe de esas pruebas (registros, capturas y cobertura). Se vuelve a generar al ejecutarlas otra vez.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "test_output", marcadores: ["Fastfile"],
                       descripcion: "informes de pruebas de fastlane",
                       consecuencia: "Se vuelven a generar al ejecutar «fastlane scan».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".aws-sam", marcadores: ["template.yaml", "template.yml", "samconfig.toml", "samconfig.yaml"],
                       descripcion: "compilación de AWS SAM",
                       consecuencia: "Se vuelve a generar con «sam build»."),
        ReglaArtefacto(carpeta: ".firebase", marcadores: ["firebase.json"],
                       descripcion: "caché de despliegue de Firebase Hosting",
                       consecuencia: "Firebase la vuelve a crear en el próximo «firebase deploy» (ese despliegue comparará y subirá los archivos otra vez)."),
        ReglaArtefacto(carpeta: "bin", marcadores: [".classpath"],
                       descripcion: "compilación de Eclipse (Java)",
                       consecuencia: "Eclipse la vuelve a generar al compilar el proyecto.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "Derived", marcadores: ["Project.swift", "Workspace.swift", "Tuist.swift"],
                       descripcion: "archivos generados por Tuist",
                       consecuencia: "Se vuelven a generar con «tuist generate».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "temp", marcadores: ["comfyui_version.py", "folder_paths.py"],
                       descripcion: "temporales de ComfyUI",
                       consecuencia: "Nada: ComfyUI la vacía cada vez que arranca. Tus imágenes de output/ no se tocan."),
        ReglaArtefacto(carpeta: "installer_files", marcadores: ["start_macos.sh"],
                       descripcion: "entorno de Python de text-generation-webui",
                       consecuencia: "Se vuelve a crear al ejecutar start_macos.sh (descarga varios GB). Tus modelos y personajes no se tocan.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: ".virtual_documents", marcadores: ["*.ipynb", ".ipynb_checkpoints"],
                       descripcion: "copias para el autocompletado de JupyterLab",
                       consecuencia: "Nada: jupyterlab-lsp las vuelve a crear al abrir un cuaderno."),
        ReglaArtefacto(carpeta: "catboost_info", marcadores: ["*.py", "*.ipynb"],
                       descripcion: "registros de entrenamiento de CatBoost",
                       consecuencia: "Se pierden las curvas de entrenamientos pasados y, si usaste save_snapshot, la copia para reanudar un entrenamiento a medias. Tus modelos guardados no se tocan."),
        ReglaArtefacto(carpeta: "__marimo__", marcadores: ["*.py"],
                       descripcion: "caché y sesiones de marimo",
                       consecuencia: "marimo recalcula las salidas guardadas y la caché persistente (mo.persistent_cache) la próxima vez; tus cuadernos (.py) no se tocan.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: ".quarto", marcadores: ["_quarto.yml", "_quarto.yaml", "*.qmd"],
                       descripcion: "carpeta interna de Quarto",
                       consecuencia: "Quarto la vuelve a crear al renderizar."),
        ReglaArtefacto(carpeta: "_freeze", marcadores: ["_quarto.yml", "_quarto.yaml"],
                       descripcion: "resultados congelados de Quarto",
                       consecuencia: "Quarto volverá a ejecutar todo el código de tus documentos al renderizar (puede tardar mucho).",
                       riesgo: .revisar, soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "_site", marcadores: ["_quarto.yml", "_quarto.yaml"],
                       descripcion: "sitio web generado por Quarto",
                       consecuencia: "Se vuelve a generar con «quarto render».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "_book", marcadores: ["_quarto.yml", "_quarto.yaml", "_bookdown.yml"],
                       descripcion: "libro generado (Quarto o bookdown)",
                       consecuencia: "Se vuelve a generar al renderizar el libro.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "_bookdown_files", marcadores: ["_bookdown.yml", "index.Rmd"],
                       descripcion: "archivos intermedios de bookdown",
                       consecuencia: "bookdown los vuelve a generar al compilar; si había caché de código, se volverá a ejecutar todo (puede tardar).",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "library", marcadores: ["activate.R"],
                       descripcion: "paquetes de R del proyecto (renv)",
                       consecuencia: "Ejecuta «renv::restore()» antes de volver a usar el proyecto. Los paquetes que instalaste sin hacer «renv::snapshot()» no se recuperan solos.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "staging", marcadores: ["activate.R"],
                       descripcion: "temporales de instalación de renv",
                       consecuencia: "Nada: renv la usa solo mientras instala paquetes."),
        ReglaArtefacto(carpeta: "python", marcadores: ["activate.R"],
                       descripcion: "entorno de Python gestionado por renv",
                       consecuencia: "renv lo vuelve a crear con renv::restore() o renv::use_python(); los paquetes de Python que no estén en requirements.txt habrá que reinstalarlos.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "lib*", marcadores: ["packrat.lock"],
                       descripcion: "paquetes de R del proyecto (packrat)",
                       consecuencia: "Ejecuta «packrat::restore()» antes de volver a usar el proyecto; en proyectos antiguos la reinstalación puede fallar.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "_build", marcadores: ["_toc.yml", "myst.yml"],
                       descripcion: "libro generado por Jupyter Book",
                       consecuencia: "Se vuelve a generar con «jupyter-book build» (o «myst build»); los cuadernos se volverán a ejecutar si la caché estaba dentro.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".jupyter_cache", marcadores: ["*.ipynb", "_toc.yml", "myst.yml"],
                       descripcion: "caché de ejecución de cuadernos",
                       consecuencia: "Los cuadernos se volverán a ejecutar la próxima vez que construyas el libro o la documentación (puede tardar mucho o necesitar datos que ya no tengas).",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "gradio_cached_examples", marcadores: ["*.py", "*.ipynb"],
                       descripcion: "ejemplos precalculados de Gradio 4",
                       consecuencia: "Gradio los vuelve a calcular la próxima vez que arranques la app."),
        ReglaArtefacto(carpeta: ".aider.tags.cache.v*", marcadores: [".git"],
                       descripcion: "caché del mapa de código de aider",
                       consecuencia: "aider la vuelve a crear la próxima vez que lo abras en ese repositorio."),
        ReglaArtefacto(carpeta: "Adobe Premiere Pro Video Previews", marcadores: ["*.prproj"],
                       descripcion: "vistas previas de vídeo de Premiere",
                       consecuencia: "Premiere las vuelve a renderizar cuando reproduzcas la secuencia (barra roja o amarilla). Tu proyecto y tus vídeos no se tocan."),
        ReglaArtefacto(carpeta: "Adobe Premiere Pro Audio Previews", marcadores: ["*.prproj"],
                       descripcion: "vistas previas de audio de Premiere",
                       consecuencia: "Premiere las vuelve a generar cuando hagan falta. Tu proyecto y tus vídeos no se tocan."),
        ReglaArtefacto(carpeta: "* Smart Previews.lrdata", marcadores: ["*.lrcat"],
                       descripcion: "vistas previas inteligentes de Lightroom Classic",
                       consecuencia: "Si tus fotos originales están en un disco desconectado, ya no podrás editarlas hasta conectarlo. Lightroom puede volver a crearlas (Biblioteca › Vistas previas). Tus fotos y ediciones no se tocan.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "* Previews.lrdata", marcadores: ["*.lrcat"],
                       descripcion: "vistas previas de Lightroom Classic",
                       consecuencia: "Lightroom las vuelve a crear al navegar por tus fotos (al principio irá más lento). Si tus originales están en un disco desconectado, verás las fotos en gris hasta que lo conectes. Tus fotos y ediciones no se tocan.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "Cache", marcadores: ["*.cocatalogdb"],
                       descripcion: "caché de un catálogo de Capture One",
                       consecuencia: "Capture One vuelve a crear miniaturas y vistas previas al navegar (tarda en catálogos grandes). Si tus originales están en un disco desconectado, no los verás hasta conectarlo. Tus fotos y ajustes no se tocan.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "blendcache_*", marcadores: ["*.blend"],
                       descripcion: "simulaciones horneadas de Blender",
                       consecuencia: "Tendrás que volver a hornear (bake) las simulaciones de física, humo o partículas; puede tardar horas y, si cambiaste la escena, el resultado puede no ser igual. Tu archivo .blend no se toca.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: ".utmp", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "temporales de Unity",
                       consecuencia: "Unity los vuelve a crear."),
        ReglaArtefacto(carpeta: "MemoryCaptures", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "capturas del Memory Profiler de Unity",
                       consecuencia: "Se pierden las capturas de memoria que guardaste para analizar. El proyecto no se toca.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "Recordings", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "grabaciones de Unity Recorder",
                       consecuencia: "Se pierden los vídeos e imágenes que grabaste con Unity Recorder y no se pueden regenerar solos: revisa antes lo que quieras conservar. El proyecto no se toca.",
                       riesgo: .revisar, soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "Build", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "compilaciones del juego (Unity)",
                       consecuencia: "Se pierden los juegos ya compilados y los proyectos de Xcode o Android Studio exportados (con los cambios que les hayas hecho a mano). Vuelve a generarlos con File › Build; si es una versión publicada, cópiala antes.",
                       riesgo: .revisar, soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "Builds", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "compilaciones del juego (Unity)",
                       consecuencia: "Se pierden los juegos ya compilados y los proyectos de Xcode o Android Studio exportados (con los cambios que les hayas hecho a mano). Vuelve a generarlos con File › Build; si es una versión publicada, cópiala antes.",
                       riesgo: .revisar, soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "ServerData", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "contenido remoto de Addressables (Unity)",
                       consecuencia: "Se vuelve a generar al compilar los Addressables. Si lo subes a un servidor, súbelo de nuevo después.",
                       riesgo: .revisar, soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".mono", marcadores: ["project.godot"],
                       descripcion: "compilación de C# de Godot 3",
                       consecuencia: "Godot la vuelve a generar al compilar el proyecto."),
        ReglaArtefacto(carpeta: ".internal", marcadores: ["game.project"],
                       descripcion: "caché del editor de Defold",
                       consecuencia: "Defold la vuelve a crear al abrir el proyecto."),
        ReglaArtefacto(carpeta: "build", marcadores: ["game.project"],
                       descripcion: "compilación de Defold",
                       consecuencia: "Defold la vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: ".ruby-lsp", marcadores: ["Gemfile"],
                       descripcion: "datos de Ruby LSP",
                       consecuencia: "El editor los vuelve a crear."),
        ReglaArtefacto(carpeta: "buildtrees", marcadores: [".vcpkg-root"],
                       descripcion: "compilaciones intermedias de vcpkg",
                       consecuencia: "Nada: las librerías ya están instaladas."),
        ReglaArtefacto(carpeta: "packages", marcadores: [".vcpkg-root"],
                       descripcion: "paquetes temporales de vcpkg",
                       consecuencia: "Nada: las librerías ya están en installed/."),
        ReglaArtefacto(carpeta: "downloads", marcadores: [".vcpkg-root"],
                       descripcion: "descargas de vcpkg",
                       consecuencia: "vcpkg vuelve a descargar el código y las herramientas que necesite."),
        ReglaArtefacto(carpeta: "ExportedObj", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "exportaciones temporales de Unity",
                       consecuencia: "Se vuelven a generar."),
        ReglaArtefacto(carpeta: "UIElementsSchema", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "esquemas generados de UI Toolkit (Unity)",
                       consecuencia: "Unity los vuelve a generar al actualizar los esquemas UXML."),
        ReglaArtefacto(carpeta: "TestResults", marcadores: ["*.csproj", "*.fsproj", "*.sln", "*.slnx"],
                       descripcion: "resultados de pruebas de .NET",
                       consecuencia: "Se regeneran al ejecutar «dotnet test»."),
        ReglaArtefacto(carpeta: "artifacts", marcadores: ["Directory.Build.props"],
                       descripcion: "compilación de .NET (salida «artifacts»)",
                       consecuencia: "Se vuelve a generar con «dotnet build».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "packages", marcadores: ["*.sln"],
                       descripcion: "paquetes NuGet restaurados",
                       consecuencia: "Se vuelven a descargar al restaurar o compilar la solución.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "BenchmarkDotNet.Artifacts", marcadores: ["*.csproj", "*.fsproj", "*.sln"],
                       descripcion: "resultados de BenchmarkDotNet",
                       consecuencia: "Pierdes los informes de mediciones anteriores. Se regeneran al volver a medir, lo que puede tardar.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: ".ionide", marcadores: ["*.fsproj", "*.sln", "*.fsx"],
                       descripcion: "caché de Ionide (F#)",
                       consecuencia: "Ionide la vuelve a crear."),
        ReglaArtefacto(carpeta: ".apt_generated", marcadores: [".classpath", ".factorypath"],
                       descripcion: "código generado por procesadores de anotaciones (Java)",
                       consecuencia: "Se vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: ".apt_generated_tests", marcadores: [".classpath", ".factorypath"],
                       descripcion: "código generado por procesadores de anotaciones (pruebas Java)",
                       consecuencia: "Se vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: "allure-results", marcadores: ["package.json", "pom.xml", "build.gradle", "build.gradle.kts", "pyproject.toml", "wdio.conf.ts", "wdio.conf.js"],
                       descripcion: "resultados de pruebas para Allure",
                       consecuencia: "Se regeneran al ejecutar las pruebas."),
        ReglaArtefacto(carpeta: "allure-report", marcadores: ["package.json", "pom.xml", "build.gradle", "build.gradle.kts", "pyproject.toml", "wdio.conf.ts", "wdio.conf.js"],
                       descripcion: "informe de Allure",
                       consecuencia: "Se regenera con «allure generate»."),
        ReglaArtefacto(carpeta: ".allure", marcadores: ["pom.xml"],
                       descripcion: "herramienta de informes Allure descargada por Maven",
                       consecuencia: "El plugin de Maven lo vuelve a descargar."),
        ReglaArtefacto(carpeta: "vcpkg_installed", marcadores: ["vcpkg.json"],
                       descripcion: "dependencias de vcpkg",
                       consecuencia: "vcpkg las vuelve a instalar al configurar o compilar, lo que puede tardar."),
        ReglaArtefacto(carpeta: ".pio", marcadores: ["platformio.ini"],
                       descripcion: "compilación y librerías de PlatformIO",
                       consecuencia: "PlatformIO vuelve a compilar y a descargar las librerías. Si no fijaste versiones en platformio.ini, puede bajar otras más nuevas. Los cambios que hiciste a mano en .pio/libdeps se pierden.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "managed_components", marcadores: ["dependencies.lock", "sdkconfig"],
                       descripcion: "componentes descargados de ESP-IDF",
                       consecuencia: "Se vuelven a descargar al compilar con «idf.py build»."),
        ReglaArtefacto(carpeta: ".xmake", marcadores: ["xmake.lua"],
                       descripcion: "caché de xmake",
                       consecuencia: "xmake la vuelve a crear."),
        ReglaArtefacto(carpeta: "build", marcadores: ["xmake.lua"],
                       descripcion: "compilación de xmake",
                       consecuencia: "Se vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: "autom4te.cache", marcadores: ["configure.ac", "configure.in"],
                       descripcion: "caché de Autoconf",
                       consecuencia: "Autoconf la vuelve a generar."),
        ReglaArtefacto(carpeta: ".ccls-cache", marcadores: ["compile_commands.json", ".ccls", "CMakeLists.txt"],
                       descripcion: "índice de ccls (C/C++)",
                       consecuencia: "ccls vuelve a indexar el proyecto."),
        ReglaArtefacto(carpeta: ".cache", marcadores: ["compile_commands.json", ".clangd", "build/compile_commands.json"],
                       descripcion: "índice de clangd (C/C++)",
                       consecuencia: "clangd vuelve a indexar el proyecto.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "out", marcadores: ["CMakePresets.json", "CMakeSettings.json"],
                       descripcion: "compilación de CMake",
                       consecuencia: "Se vuelve a generar al configurar y compilar.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "builddir", marcadores: ["meson.build"],
                       descripcion: "compilación de Meson",
                       consecuencia: "Se vuelve a generar con «meson setup»."),
        ReglaArtefacto(carpeta: "build", marcadores: ["build/meson-private"],
                       descripcion: "compilación de Meson",
                       consecuencia: "Se vuelve a generar con «meson setup»."),
        ReglaArtefacto(carpeta: "Debug", marcadores: ["Debug/objects.mk", "Debug/sources.mk"],
                       descripcion: "compilación de Eclipse CDT o STM32CubeIDE",
                       consecuencia: "Se vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: "Release", marcadores: ["Release/objects.mk", "Release/sources.mk"],
                       descripcion: "compilación de Eclipse CDT o STM32CubeIDE",
                       consecuencia: "Se vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: "buck-out", marcadores: [".buckconfig"],
                       descripcion: "compilación de Buck",
                       consecuencia: "Se vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: ".pants.d", marcadores: ["pants.toml"],
                       descripcion: "trabajo interno de Pants",
                       consecuencia: "Pants lo vuelve a crear."),
        ReglaArtefacto(carpeta: "plz-out", marcadores: [".plzconfig"],
                       descripcion: "compilación de Please",
                       consecuencia: "Se vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: "temp", marcadores: ["config/rush"],
                       descripcion: "instalación compartida de Rush",
                       consecuencia: "Ejecuta «rush install» antes de volver a usar el monorepo.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".nx", marcadores: ["nx.json"],
                       descripcion: "caché de Nx",
                       consecuencia: "Nx la vuelve a crear. La primera ejecución de tareas irá más lenta."),
        ReglaArtefacto(carpeta: ".vercel", marcadores: ["vercel.json", "package.json"],
                       descripcion: "vínculo y compilación local de Vercel",
                       consecuencia: "Tendrás que volver a ejecutar «vercel link» (y «vercel pull» si usas sus variables). La compilación local se regenera.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: ".netlify", marcadores: ["netlify.toml", "package.json"],
                       descripcion: "datos locales de Netlify CLI",
                       consecuencia: "Tendrás que volver a vincular el sitio con «netlify link» y pierdes los datos de prueba locales.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: ".amplify", marcadores: ["amplify/backend.ts", "amplify_outputs.json"],
                       descripcion: "archivos generados de Amplify Gen 2",
                       consecuencia: "Se vuelven a generar al ejecutar el sandbox de Amplify."),
        ReglaArtefacto(carpeta: "#current-cloud-backend", marcadores: ["cli.json", "team-provider-info.json"],
                       descripcion: "copia del backend desplegado (Amplify)",
                       consecuencia: "Ejecuta «amplify pull» antes de volver a desplegar. Sin esta copia, Amplify no sabe qué cambió.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "packer_cache", marcadores: ["*.pkr.hcl", "*.pkr.json"],
                       descripcion: "descargas de Packer",
                       consecuencia: "Packer vuelve a descargar las imágenes ISO si las necesita."),
        ReglaArtefacto(carpeta: ".direnv", marcadores: [".envrc"],
                       descripcion: "entornos de direnv",
                       consecuencia: "direnv vuelve a crear los entornos al entrar en la carpeta, pero vacíos: tendrás que reinstalar los paquetes de Python, Ruby, Perl o Go que instalaste en ellos. Con Nix, el entorno se vuelve a construir o descargar.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: ".open-next", marcadores: ["open-next.config.ts", "open-next.config.js", "wrangler.jsonc", "wrangler.toml"],
                       descripcion: "compilación de OpenNext",
                       consecuencia: "Se vuelve a generar al compilar o desplegar."),
        ReglaArtefacto(carpeta: ".output", marcadores: ["nitro.config.ts", "nitro.config.js"],
                       descripcion: "compilación de Nitro",
                       consecuencia: "Se vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: ".nitro", marcadores: ["nitro.config.ts", "nitro.config.js"],
                       descripcion: "compilación de desarrollo de Nitro",
                       consecuencia: "Se vuelve a generar al ejecutar el servidor."),
        ReglaArtefacto(carpeta: ".vinxi", marcadores: ["app.config.ts", "app.config.js"],
                       descripcion: "compilación de Vinxi (SolidStart, TanStack Start)",
                       consecuencia: "Se vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: ".quasar", marcadores: ["quasar.config.js", "quasar.config.ts", "quasar.config.mjs", "quasar.conf.js"],
                       descripcion: "archivos generados de Quasar",
                       consecuencia: "Quasar los vuelve a generar."),
        ReglaArtefacto(carpeta: ".umi", marcadores: [".umirc.ts", ".umirc.js", "config/config.ts", "config/config.js", "../.umirc.ts", "../.umirc.js", "../config/config.ts", "../config/config.js"],
                       descripcion: "archivos generados de UmiJS",
                       consecuencia: "Umi los vuelve a generar."),
        ReglaArtefacto(carpeta: ".umi-production", marcadores: [".umirc.ts", ".umirc.js", "config/config.ts", "config/config.js", "../.umirc.ts", "../.umirc.js", "../config/config.ts", "../config/config.js"],
                       descripcion: "archivos generados de UmiJS",
                       consecuencia: "Umi los vuelve a generar."),
        ReglaArtefacto(carpeta: ".react-router", marcadores: ["react-router.config.ts", "react-router.config.js"],
                       descripcion: "tipos generados de React Router",
                       consecuencia: "Se vuelven a generar al compilar o con «react-router typegen»."),
        ReglaArtefacto(carpeta: ".tanstack", marcadores: ["package.json"],
                       descripcion: "temporales de TanStack Router",
                       consecuencia: "Se vuelven a crear."),
        ReglaArtefacto(carpeta: ".react-email", marcadores: ["package.json"],
                       descripcion: "vista previa compilada de React Email",
                       consecuencia: "Se vuelve a generar con «email build»."),
        ReglaArtefacto(carpeta: ".medusa", marcadores: ["medusa-config.ts", "medusa-config.js"],
                       descripcion: "compilación de Medusa",
                       consecuencia: "Se vuelve a generar con «medusa build»."),
        ReglaArtefacto(carpeta: ".strapi", marcadores: ["config/admin.ts", "config/admin.js"],
                       descripcion: "panel de administración compilado de Strapi",
                       consecuencia: "Strapi lo vuelve a generar al arrancar en modo desarrollo o al compilar."),
        ReglaArtefacto(carpeta: ".keystone", marcadores: ["keystone.ts", "keystone.js"],
                       descripcion: "panel de administración compilado de Keystone",
                       consecuencia: "Keystone lo vuelve a generar."),
        ReglaArtefacto(carpeta: ".redwood", marcadores: ["redwood.toml"],
                       descripcion: "archivos generados de RedwoodJS",
                       consecuencia: "Redwood los vuelve a generar."),
        ReglaArtefacto(carpeta: ".contentlayer", marcadores: ["contentlayer.config.ts", "contentlayer.config.js", "contentlayer.config.mjs"],
                       descripcion: "contenido generado por Contentlayer",
                       consecuencia: "Se vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: ".velite", marcadores: ["velite.config.ts", "velite.config.js"],
                       descripcion: "contenido generado por Velite",
                       consecuencia: "Se vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: ".source", marcadores: ["source.config.ts"],
                       descripcion: "archivos generados de Fumadocs",
                       consecuencia: "Se vuelven a generar al compilar."),
        ReglaArtefacto(carpeta: ".content-collections", marcadores: ["content-collections.ts"],
                       descripcion: "contenido generado por Content Collections",
                       consecuencia: "Se vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: ".tamagui", marcadores: ["tamagui.config.ts", "tamagui.config.js"],
                       descripcion: "caché del compilador de Tamagui",
                       consecuencia: "Tamagui la vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: ".cache", marcadores: ["package.json"],
                       descripcion: "caché de herramientas web",
                       consecuencia: "Se regenera al compilar.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".npm", marcadores: ["package.json"],
                       descripcion: "caché de npm del proyecto",
                       consecuencia: "npm vuelve a descargar los paquetes si hacen falta.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "bower_components", marcadores: ["bower.json"],
                       descripcion: "dependencias de Bower",
                       consecuencia: "Ejecuta «bower install» antes de volver a usar el proyecto. Bower ya no se mantiene y no fija versiones exactas: puede que no se reinstalen igual.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "jspm_packages", marcadores: ["package.json"],
                       descripcion: "dependencias de jspm",
                       consecuencia: "Ejecuta «jspm install» antes de volver a usar el proyecto. En proyectos antiguos puede que ya no se reinstalen.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: ".rpt2_cache", marcadores: ["rollup.config.js", "rollup.config.ts", "rollup.config.mjs"],
                       descripcion: "caché de rollup-plugin-typescript2",
                       consecuencia: "Se regenera al compilar."),
        ReglaArtefacto(carpeta: ".rollup.cache", marcadores: ["package.json"],
                       descripcion: "caché de compilación de Rollup",
                       consecuencia: "Se regenera al compilar."),
        ReglaArtefacto(carpeta: ".webpack", marcadores: ["forge.config.js", "forge.config.ts", "forge.config.cjs"],
                       descripcion: "compilación de Electron Forge (webpack)",
                       consecuencia: "Se vuelve a generar al ejecutar o empaquetar la app."),
        ReglaArtefacto(carpeta: "release", marcadores: ["electron-builder.yml", "electron-builder.yaml", "electron-builder.json", "electron-builder.json5", "electron-builder.config.js"],
                       descripcion: "instaladores generados por electron-builder",
                       consecuencia: "Se borran los instaladores (.dmg, .zip, .exe) que generaste, también los de versiones anteriores. Al empaquetar solo se regenera la versión actual del código.",
                       riesgo: .revisar, soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "dist_electron", marcadores: ["vue.config.js"],
                       descripcion: "compilación de Electron (Vue CLI)",
                       consecuencia: "Se vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: "lib", marcadores: ["tsconfig.json"],
                       descripcion: "código JavaScript compilado desde TypeScript",
                       consecuencia: "Se vuelve a generar al compilar.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".cache", marcadores: ["../playwright-ct.config.ts", "../playwright-ct.config.js", "../playwright-ct.config.mjs"],
                       descripcion: "caché de pruebas de componentes de Playwright",
                       consecuencia: "Se regenera al ejecutar las pruebas.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "screenshots", marcadores: ["support/e2e.ts", "support/e2e.js", "support/commands.ts", "support/commands.js", "support/component.ts", "support/component.js", "support/index.js"],
                       descripcion: "capturas de pruebas de Cypress",
                       consecuencia: "Se regeneran al ejecutar las pruebas.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "videos", marcadores: ["support/e2e.ts", "support/e2e.js", "support/commands.ts", "support/commands.js", "support/component.ts", "support/component.js", "support/index.js"],
                       descripcion: "vídeos de pruebas de Cypress",
                       consecuencia: "Se regeneran al ejecutar las pruebas.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "downloads", marcadores: ["support/e2e.ts", "support/e2e.js", "support/commands.ts", "support/commands.js", "support/component.ts", "support/component.js", "support/index.js"],
                       descripcion: "descargas de pruebas de Cypress",
                       consecuencia: "Se regeneran al ejecutar las pruebas.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "artifacts", marcadores: [".detoxrc.js", ".detoxrc.json", ".detoxrc", ".detoxrc.cjs", "detox.config.js"],
                       descripcion: "grabaciones y registros de Detox",
                       consecuencia: "Se regeneran al ejecutar las pruebas.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".vscode-test", marcadores: ["package.json", ".vscode-test.mjs", ".vscode-test.js", ".vscode-test.cjs"],
                       descripcion: "copia de VS Code para probar extensiones",
                       consecuencia: "Se vuelve a descargar al ejecutar las pruebas de la extensión."),
        ReglaArtefacto(carpeta: ".vscode-test-web", marcadores: ["package.json"],
                       descripcion: "copia de VS Code web para probar extensiones",
                       consecuencia: "Se vuelve a descargar al ejecutar las pruebas."),
        ReglaArtefacto(carpeta: "web-build", marcadores: ["app.json", "app.config.js", "app.config.ts"],
                       descripcion: "compilación web de Expo",
                       consecuencia: "Se vuelve a generar al exportar la web.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "www", marcadores: ["capacitor.config.ts", "capacitor.config.json", "ionic.config.json"],
                       descripcion: "web compilada de Ionic o Capacitor",
                       consecuencia: "Se vuelve a generar al compilar la web.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "public", marcadores: ["capacitor.config.json"],
                       descripcion: "copia de la web dentro de la app nativa (Capacitor)",
                       consecuencia: "Se vuelve a copiar con «npx cap sync».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "platforms", marcadores: ["nativescript.config.ts", "nativescript.config.js"],
                       descripcion: "proyectos nativos generados por NativeScript",
                       consecuencia: "NativeScript los vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: "platforms", marcadores: ["config.xml"],
                       descripcion: "proyectos nativos generados por Cordova",
                       consecuencia: "Se vuelven a generar con «cordova prepare». Si cambiaste algo a mano ahí, se pierde.",
                       riesgo: .revisar, soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "plugins", marcadores: ["config.xml"],
                       descripcion: "plugins descargados de Cordova",
                       consecuencia: "Se vuelven a descargar con «cordova prepare».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "captures", marcadores: ["build.gradle", "build.gradle.kts", "settings.gradle", "settings.gradle.kts"],
                       descripcion: "capturas del perfilador de Android Studio",
                       consecuencia: "Pierdes las trazas y volcados de memoria que guardaste para analizar la app.",
                       riesgo: .revisar, soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "screenshots", marcadores: ["Fastfile", "Snapfile", "Screengrabfile"],
                       descripcion: "capturas para las tiendas generadas por fastlane",
                       consecuencia: "Se vuelven a generar con «fastlane snapshot» o «screengrab». Si las retocaste a mano, se pierden.",
                       riesgo: .revisar, soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "ephemeral", marcadores: ["Generated.xcconfig", "Flutter-Debug.xcconfig", "AppFrameworkInfo.plist", "generated_plugins.cmake"],
                       descripcion: "archivos temporales de Flutter para la plataforma",
                       consecuencia: "Flutter los vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: "coverage", marcadores: ["pubspec.yaml", "Gemfile", "mix.exs", "Cargo.toml", "go.mod", "composer.json"],
                       descripcion: "informe de cobertura de pruebas",
                       consecuencia: "Se regenera al ejecutar las pruebas con cobertura.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".widget_preview", marcadores: ["pubspec.yaml"],
                       descripcion: "vista previa de widgets de Flutter",
                       consecuencia: "Flutter la vuelve a generar al abrir la vista previa de widgets."),
        ReglaArtefacto(carpeta: "api", marcadores: ["api/__404error.html"],
                       descripcion: "documentación generada por dart doc",
                       consecuencia: "Se vuelve a generar con «dart doc».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "htmlcov", marcadores: ["pyproject.toml", "setup.py", "setup.cfg", ".coveragerc", "tox.ini"],
                       descripcion: "informe de cobertura de Python",
                       consecuencia: "Se regenera con «coverage html»."),
        ReglaArtefacto(carpeta: ".hypothesis", marcadores: ["pyproject.toml", "setup.py", "setup.cfg", "pytest.ini", "tox.ini"],
                       descripcion: "base de ejemplos de Hypothesis",
                       consecuencia: "Hypothesis la vuelve a crear. Los fallos encontrados antes no se repetirán primero."),
        ReglaArtefacto(carpeta: ".pyre", marcadores: [".pyre_configuration", "pyproject.toml"],
                       descripcion: "caché de Pyre",
                       consecuencia: "Pyre la vuelve a generar."),
        ReglaArtefacto(carpeta: ".pytype", marcadores: ["pyproject.toml", "setup.cfg", "setup.py"],
                       descripcion: "caché de pytype",
                       consecuencia: "pytype la vuelve a generar."),
        ReglaArtefacto(carpeta: "cython_debug", marcadores: ["setup.py", "pyproject.toml"],
                       descripcion: "datos de depuración de Cython",
                       consecuencia: "Se regeneran al compilar con depuración."),
        ReglaArtefacto(carpeta: "__pypackages__", marcadores: ["pyproject.toml"],
                       descripcion: "paquetes del proyecto (PEP 582)",
                       consecuencia: "Ejecuta «pdm install» antes de volver a usar el proyecto."),
        ReglaArtefacto(carpeta: ".pdm-build", marcadores: ["pyproject.toml"],
                       descripcion: "compilación de PDM",
                       consecuencia: "Se vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: "wheelhouse", marcadores: ["pyproject.toml", "setup.py"],
                       descripcion: "paquetes wheel generados",
                       consecuencia: "Se vuelven a generar con cibuildwheel o «pip wheel».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "site", marcadores: ["mkdocs.yml", "mkdocs.yaml"],
                       descripcion: "sitio compilado de MkDocs",
                       consecuencia: "Se vuelve a generar con «mkdocs build».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "_build", marcadores: ["conf.py", "source/conf.py"],
                       descripcion: "documentación compilada de Sphinx",
                       consecuencia: "Se vuelve a generar con «make html»."),
        ReglaArtefacto(carpeta: ".scrapy", marcadores: ["scrapy.cfg"],
                       descripcion: "caché HTTP de Scrapy",
                       consecuencia: "Scrapy vuelve a descargar las páginas; las que ya no existan en la web no se recuperan. Si usas scrapy-deltafetch, volverá a procesar elementos que ya tenías.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "staticfiles", marcadores: ["manage.py"],
                       descripcion: "archivos estáticos recopilados de Django",
                       consecuencia: "Se vuelven a generar con «manage.py collectstatic».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".yardoc", marcadores: ["Gemfile", "*.gemspec", ".yardopts"],
                       descripcion: "caché de YARD (Ruby)",
                       consecuencia: "YARD la vuelve a generar."),
        ReglaArtefacto(carpeta: "pkg", marcadores: ["*.gemspec"],
                       descripcion: "gemas empaquetadas",
                       consecuencia: "Se vuelven a generar con «rake build».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".phpunit.cache", marcadores: ["phpunit.xml", "phpunit.xml.dist", "phpunit.dist.xml"],
                       descripcion: "caché de PHPUnit",
                       consecuencia: "PHPUnit la vuelve a crear."),
        ReglaArtefacto(carpeta: "build", marcadores: ["../artisan"],
                       descripcion: "recursos compilados de Laravel (Vite)",
                       consecuencia: "Se vuelven a generar con «npm run build».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "build", marcadores: ["../remix.config.js", "../remix.config.mjs"],
                       descripcion: "recursos compilados de Remix",
                       consecuencia: "Se vuelven a generar al compilar.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "vendor", marcadores: ["go.mod"],
                       descripcion: "dependencias copiadas de Go",
                       consecuencia: "Go usa su caché de módulos o los vuelve a descargar. Si el proyecto los necesita copiados, ejecuta «go mod vendor».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "vendor", marcadores: ["deno.json", "deno.jsonc"],
                       descripcion: "dependencias copiadas de Deno",
                       consecuencia: "Deno las vuelve a descargar. Se pierden los cambios que hiciste a mano en esas dependencias.",
                       riesgo: .revisar, soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".elixir_ls", marcadores: ["mix.exs"],
                       descripcion: "compilación de ElixirLS",
                       consecuencia: "ElixirLS la vuelve a crear al abrir el proyecto."),
        ReglaArtefacto(carpeta: ".lexical", marcadores: ["mix.exs"],
                       descripcion: "compilación de Lexical",
                       consecuencia: "Lexical la vuelve a crear."),
        ReglaArtefacto(carpeta: "cover", marcadores: ["mix.exs"],
                       descripcion: "informe de cobertura de Elixir",
                       consecuencia: "Se regenera con «mix test --cover».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "_build", marcadores: ["rebar.config"],
                       descripcion: "compilación de Erlang (rebar3)",
                       consecuencia: "rebar3 la vuelve a generar."),
        ReglaArtefacto(carpeta: "_build", marcadores: ["dune-project"],
                       descripcion: "compilación de OCaml (dune)",
                       consecuencia: "dune la vuelve a generar."),
        ReglaArtefacto(carpeta: "_opam", marcadores: ["dune-project", "*.opam"],
                       descripcion: "entorno local de opam (OCaml)",
                       consecuencia: "Tendrás que recrearlo con «opam switch create . --deps-only», que tarda bastante.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "build", marcadores: ["gleam.toml"],
                       descripcion: "compilación de Gleam",
                       consecuencia: "Gleam la vuelve a generar."),
        ReglaArtefacto(carpeta: ".cpcache", marcadores: ["deps.edn"],
                       descripcion: "caché de Clojure CLI",
                       consecuencia: "Clojure la vuelve a crear."),
        ReglaArtefacto(carpeta: ".shadow-cljs", marcadores: ["shadow-cljs.edn"],
                       descripcion: "caché de shadow-cljs",
                       consecuencia: "shadow-cljs la vuelve a crear."),
        ReglaArtefacto(carpeta: "target", marcadores: ["project.clj", "deps.edn", "build.boot"],
                       descripcion: "compilación de Clojure",
                       consecuencia: "Se vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: ".scala-build", marcadores: ["project.scala", "*.scala", "*.sc"],
                       descripcion: "compilación de Scala CLI",
                       consecuencia: "Scala CLI la vuelve a generar."),
        ReglaArtefacto(carpeta: "out", marcadores: ["build.mill", "build.sc", "build.mill.scala"],
                       descripcion: "compilación de Mill",
                       consecuencia: "Mill la vuelve a generar.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "target", marcadores: ["../build.sbt"],
                       descripcion: "compilación de sbt (módulos)",
                       consecuencia: "sbt la vuelve a generar."),
        ReglaArtefacto(carpeta: "dist", marcadores: ["*.cabal"],
                       descripcion: "compilación antigua de Cabal",
                       consecuencia: "Cabal la vuelve a generar.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "output", marcadores: ["spago.yaml", "spago.dhall"],
                       descripcion: "compilación de PureScript",
                       consecuencia: "Se vuelve a generar con «spago build».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".spago", marcadores: ["spago.yaml", "spago.dhall"],
                       descripcion: "dependencias de Spago",
                       consecuencia: "Spago las vuelve a descargar."),
        ReglaArtefacto(carpeta: "bs", marcadores: ["bs/.compiler.log", "bs/build.ninja"],
                       descripcion: "compilación de ReScript",
                       consecuencia: "ReScript la vuelve a generar."),
        ReglaArtefacto(carpeta: "ocaml", marcadores: ["bs/.compiler.log", "bs/build.ninja"],
                       descripcion: "compilación de ReScript",
                       consecuencia: "ReScript la vuelve a generar.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "lib", marcadores: ["shard.yml"],
                       descripcion: "dependencias de Crystal (shards)",
                       consecuencia: "Ejecuta «shards install» antes de volver a usar el proyecto.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".dub", marcadores: ["dub.json", "dub.sdl"],
                       descripcion: "compilación de DUB (D)",
                       consecuencia: "DUB la vuelve a generar."),
        ReglaArtefacto(carpeta: "slprj", marcadores: ["*.slx", "*.mdl", "*.prj"],
                       descripcion: "caché de Simulink",
                       consecuencia: "Simulink la vuelve a generar al simular o compilar."),
        ReglaArtefacto(carpeta: "_gen", marcadores: ["../hugo.toml", "../hugo.yaml", "../hugo.json", "../archetypes"],
                       descripcion: "recursos generados por Hugo",
                       consecuencia: "Hugo los vuelve a generar."),
        ReglaArtefacto(carpeta: "public", marcadores: ["hugo.toml", "hugo.yaml", "hugo.json", "archetypes"],
                       descripcion: "sitio compilado de Hugo",
                       consecuencia: "Se vuelve a generar con «hugo».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "public", marcadores: ["scaffolds"],
                       descripcion: "sitio compilado de Hexo",
                       consecuencia: "Se vuelve a generar con «hexo generate».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".deploy_git", marcadores: ["_config.yml"],
                       descripcion: "copia de despliegue de Hexo",
                       consecuencia: "Se vuelve a crear con «hexo deploy»."),
        ReglaArtefacto(carpeta: "_site", marcadores: ["eleventy.config.js", "eleventy.config.mjs", "eleventy.config.cjs", "eleventy.config.ts", ".eleventy.js"],
                       descripcion: "sitio compilado de Eleventy",
                       consecuencia: "Se vuelve a generar con Eleventy."),
        ReglaArtefacto(carpeta: "book", marcadores: ["book.toml"],
                       descripcion: "libro compilado de mdBook",
                       consecuencia: "Se vuelve a generar con «mdbook build».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "output", marcadores: ["pelicanconf.py"],
                       descripcion: "sitio compilado de Pelican",
                       consecuencia: "Se vuelve a generar con «pelican».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "html", marcadores: ["Doxyfile"],
                       descripcion: "documentación generada por Doxygen",
                       consecuencia: "Se vuelve a generar con «doxygen».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "latex", marcadores: ["Doxyfile"],
                       descripcion: "documentación generada por Doxygen",
                       consecuencia: "Se vuelve a generar con «doxygen».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "_minted*", marcadores: ["*.tex"],
                       descripcion: "caché de minted (LaTeX)",
                       consecuencia: "LaTeX la vuelve a generar al compilar."),
        ReglaArtefacto(carpeta: "svg-inkscape", marcadores: ["*.tex"],
                       descripcion: "conversiones de SVG para LaTeX",
                       consecuencia: "LaTeX las vuelve a generar al compilar."),
    ]
}
