import Foundation

/// Más carpetas regenerables dentro de proyectos (segunda tanda, verificada).
extension Catalogo {
    static let artefactosExtra: [ReglaArtefacto] = [
        ReglaArtefacto(carpeta: "SourcePackages", marcadores: ["*.xcodeproj", "*.xcworkspace"],
                       descripcion: "paquetes de Swift descargados por xcodebuild",
                       consecuencia: "Xcode los vuelve a descargar al resolver los paquetes (necesita internet).",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "*.xcresult", marcadores: ["*.xcodeproj", "*.xcworkspace", "Package.swift"],
                       descripcion: "resultados de pruebas de Xcode",
                       consecuencia: "Pierdes el informe de esas pruebas (registros, capturas y cobertura). Se vuelve a generar al ejecutarlas otra vez.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "test_output", marcadores: ["Fastfile"],
                       descripcion: "informes de pruebas de fastlane",
                       consecuencia: "Se vuelven a generar al ejecutar «fastlane scan».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".aws-sam", marcadores: ["template.yaml", "template.yml", "samconfig.toml", "samconfig.yaml"],
                       descripcion: "compilación de AWS SAM",
                       consecuencia: "Se vuelve a generar con «sam build»."),
        ReglaArtefacto(carpeta: ".firebase", marcadores: ["firebase.json"],
                       descripcion: "caché de despliegue de Firebase Hosting",
                       consecuencia: "Firebase la vuelve a crear en el próximo «firebase deploy» (ese despliegue comparará y subirá los archivos otra vez)."),
        ReglaArtefacto(carpeta: "bin", marcadores: [".classpath"],
                       descripcion: "compilación de Eclipse (Java)",
                       consecuencia: "Eclipse la vuelve a generar al compilar el proyecto.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "Derived", marcadores: ["Project.swift", "Workspace.swift", "Tuist.swift"],
                       descripcion: "archivos generados por Tuist",
                       consecuencia: "Se vuelven a generar con «tuist generate».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "temp", marcadores: ["comfyui_version.py", "folder_paths.py"],
                       descripcion: "temporales de ComfyUI",
                       consecuencia: "Nada: ComfyUI la vacía cada vez que arranca. Tus imágenes de output/ no se tocan."),
        ReglaArtefacto(carpeta: "installer_files", marcadores: ["start_macos.sh"],
                       descripcion: "entorno de Python de text-generation-webui",
                       consecuencia: "Se vuelve a crear al ejecutar start_macos.sh (descarga varios GB). Tus modelos y personajes no se tocan.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: ".virtual_documents", marcadores: ["*.ipynb", ".ipynb_checkpoints"],
                       descripcion: "copias para el autocompletado de JupyterLab",
                       consecuencia: "Nada: jupyterlab-lsp las vuelve a crear al abrir un cuaderno."),
        ReglaArtefacto(carpeta: "catboost_info", marcadores: ["*.py", "*.ipynb"],
                       descripcion: "registros de entrenamiento de CatBoost",
                       consecuencia: "Se pierden las curvas de entrenamientos pasados y, si usaste save_snapshot, la copia para reanudar un entrenamiento a medias. Tus modelos guardados no se tocan."),
        ReglaArtefacto(carpeta: "__marimo__", marcadores: ["*.py"],
                       descripcion: "caché y sesiones de marimo",
                       consecuencia: "marimo recalcula las salidas guardadas y la caché persistente (mo.persistent_cache) la próxima vez; tus cuadernos (.py) no se tocan.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: ".quarto", marcadores: ["_quarto.yml", "_quarto.yaml", "*.qmd"],
                       descripcion: "carpeta interna de Quarto",
                       consecuencia: "Quarto la vuelve a crear al renderizar."),
        ReglaArtefacto(carpeta: "_freeze", marcadores: ["_quarto.yml", "_quarto.yaml"],
                       descripcion: "resultados congelados de Quarto",
                       consecuencia: "Quarto volverá a ejecutar todo el código de tus documentos al renderizar (puede tardar mucho).",
                       riesgo: .revisar, soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "_site", marcadores: ["_quarto.yml", "_quarto.yaml"],
                       descripcion: "sitio web generado por Quarto",
                       consecuencia: "Se vuelve a generar con «quarto render».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "_book", marcadores: ["_quarto.yml", "_quarto.yaml", "_bookdown.yml"],
                       descripcion: "libro generado (Quarto o bookdown)",
                       consecuencia: "Se vuelve a generar al renderizar el libro.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "_bookdown_files", marcadores: ["_bookdown.yml", "index.Rmd"],
                       descripcion: "archivos intermedios de bookdown",
                       consecuencia: "bookdown los vuelve a generar al compilar; si había caché de código, se volverá a ejecutar todo (puede tardar).",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "library", marcadores: ["activate.R"],
                       descripcion: "paquetes de R del proyecto (renv)",
                       consecuencia: "Ejecuta «renv::restore()» antes de volver a usar el proyecto. Los paquetes que instalaste sin hacer «renv::snapshot()» no se recuperan solos.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "staging", marcadores: ["activate.R"],
                       descripcion: "temporales de instalación de renv",
                       consecuencia: "Nada: renv la usa solo mientras instala paquetes."),
        ReglaArtefacto(carpeta: "python", marcadores: ["activate.R"],
                       descripcion: "entorno de Python gestionado por renv",
                       consecuencia: "renv lo vuelve a crear con renv::restore() o renv::use_python(); los paquetes de Python que no estén en requirements.txt habrá que reinstalarlos.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "lib*", marcadores: ["packrat.lock"],
                       descripcion: "paquetes de R del proyecto (packrat)",
                       consecuencia: "Ejecuta «packrat::restore()» antes de volver a usar el proyecto; en proyectos antiguos la reinstalación puede fallar.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "_build", marcadores: ["_toc.yml", "myst.yml"],
                       descripcion: "libro generado por Jupyter Book",
                       consecuencia: "Se vuelve a generar con «jupyter-book build» (o «myst build»); los cuadernos se volverán a ejecutar si la caché estaba dentro.",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".jupyter_cache", marcadores: ["*.ipynb", "_toc.yml", "myst.yml"],
                       descripcion: "caché de ejecución de cuadernos",
                       consecuencia: "Los cuadernos se volverán a ejecutar la próxima vez que construyas el libro o la documentación (puede tardar mucho o necesitar datos que ya no tengas).",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "gradio_cached_examples", marcadores: ["*.py", "*.ipynb"],
                       descripcion: "ejemplos precalculados de Gradio 4",
                       consecuencia: "Gradio los vuelve a calcular la próxima vez que arranques la app."),
        ReglaArtefacto(carpeta: ".aider.tags.cache.v*", marcadores: [".git"],
                       descripcion: "caché del mapa de código de aider",
                       consecuencia: "aider la vuelve a crear la próxima vez que lo abras en ese repositorio."),
        ReglaArtefacto(carpeta: "Adobe Premiere Pro Video Previews", marcadores: ["*.prproj"],
                       descripcion: "vistas previas de vídeo de Premiere",
                       consecuencia: "Premiere las vuelve a renderizar cuando reproduzcas la secuencia (barra roja o amarilla). Tu proyecto y tus vídeos no se tocan."),
        ReglaArtefacto(carpeta: "Adobe Premiere Pro Audio Previews", marcadores: ["*.prproj"],
                       descripcion: "vistas previas de audio de Premiere",
                       consecuencia: "Premiere las vuelve a generar cuando hagan falta. Tu proyecto y tus vídeos no se tocan."),
        ReglaArtefacto(carpeta: "* Smart Previews.lrdata", marcadores: ["*.lrcat"],
                       descripcion: "vistas previas inteligentes de Lightroom Classic",
                       consecuencia: "Si tus fotos originales están en un disco desconectado, ya no podrás editarlas hasta conectarlo. Lightroom puede volver a crearlas (Biblioteca › Vistas previas). Tus fotos y ediciones no se tocan.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "* Previews.lrdata", marcadores: ["*.lrcat"],
                       descripcion: "vistas previas de Lightroom Classic",
                       consecuencia: "Lightroom las vuelve a crear al navegar por tus fotos (al principio irá más lento). Si tus originales están en un disco desconectado, verás las fotos en gris hasta que lo conectes. Tus fotos y ediciones no se tocan.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "Cache", marcadores: ["*.cocatalogdb"],
                       descripcion: "caché de un catálogo de Capture One",
                       consecuencia: "Capture One vuelve a crear miniaturas y vistas previas al navegar (tarda en catálogos grandes). Si tus originales están en un disco desconectado, no los verás hasta conectarlo. Tus fotos y ajustes no se tocan.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "blendcache_*", marcadores: ["*.blend"],
                       descripcion: "simulaciones horneadas de Blender",
                       consecuencia: "Tendrás que volver a hornear (bake) las simulaciones de física, humo o partículas; puede tardar horas y, si cambiaste la escena, el resultado puede no ser igual. Tu archivo .blend no se toca.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: ".utmp", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "temporales de Unity",
                       consecuencia: "Unity los vuelve a crear."),
        ReglaArtefacto(carpeta: "MemoryCaptures", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "capturas del Memory Profiler de Unity",
                       consecuencia: "Se pierden las capturas de memoria que guardaste para analizar. El proyecto no se toca.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "Recordings", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "grabaciones de Unity Recorder",
                       consecuencia: "Se pierden los vídeos e imágenes que grabaste con Unity Recorder y no se pueden regenerar solos: revisa antes lo que quieras conservar. El proyecto no se toca.",
                       riesgo: .revisar, soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "Build", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "compilaciones del juego (Unity)",
                       consecuencia: "Se pierden los juegos ya compilados y los proyectos de Xcode o Android Studio exportados (con los cambios que les hayas hecho a mano). Vuelve a generarlos con File › Build; si es una versión publicada, cópiala antes.",
                       riesgo: .revisar, soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "Builds", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "compilaciones del juego (Unity)",
                       consecuencia: "Se pierden los juegos ya compilados y los proyectos de Xcode o Android Studio exportados (con los cambios que les hayas hecho a mano). Vuelve a generarlos con File › Build; si es una versión publicada, cópiala antes.",
                       riesgo: .revisar, soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "ServerData", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "contenido remoto de Addressables (Unity)",
                       consecuencia: "Se vuelve a generar al compilar los Addressables. Si lo subes a un servidor, súbelo de nuevo después.",
                       riesgo: .revisar, soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".mono", marcadores: ["project.godot"],
                       descripcion: "compilación de C# de Godot 3",
                       consecuencia: "Godot la vuelve a generar al compilar el proyecto."),
        ReglaArtefacto(carpeta: ".internal", marcadores: ["game.project"],
                       descripcion: "caché del editor de Defold",
                       consecuencia: "Defold la vuelve a crear al abrir el proyecto."),
        ReglaArtefacto(carpeta: "build", marcadores: ["game.project"],
                       descripcion: "compilación de Defold",
                       consecuencia: "Defold la vuelve a generar al compilar."),
    ]
}
