import Foundation

/// Más carpetas regenerables dentro de proyectos (segunda tanda, verificada).
extension Catalogo {
    static let artefactosExtra: [ReglaArtefacto] = [
        ReglaArtefacto(carpeta: "SourcePackages", marcadores: ["*.xcodeproj", "*.xcworkspace"],
                       descripcion: "paquetes de Swift descargados por xcodebuild",
                       consecuencia: "Xcode los vuelve a descargar al resolver los paquetes (necesita internet).",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "*.xcresult", marcadores: ["*.xcodeproj", "*.xcworkspace", "Package.swift"],
                       descripcion: "resultados de pruebas de Xcode",
                       consecuencia: "Pierdes el informe de esas pruebas (registros, capturas y cobertura). Se vuelve a generar al ejecutarlas otra vez.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "test_output", marcadores: ["Fastfile"],
                       descripcion: "informes de pruebas de fastlane",
                       consecuencia: "Se vuelven a generar al ejecutar «fastlane scan».",
                       soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "Adobe Premiere Pro Video Previews", marcadores: ["*.prproj"],
                       descripcion: "vistas previas de vídeo de Premiere",
                       consecuencia: "Premiere las vuelve a renderizar cuando reproduzcas la secuencia (barra roja o amarilla). Tu proyecto y tus vídeos no se tocan."),
        ReglaArtefacto(carpeta: "Adobe Premiere Pro Audio Previews", marcadores: ["*.prproj"],
                       descripcion: "vistas previas de audio de Premiere",
                       consecuencia: "Premiere las vuelve a generar cuando hagan falta. Tu proyecto y tus vídeos no se tocan."),
        ReglaArtefacto(carpeta: "* Smart Previews.lrdata", marcadores: ["*.lrcat"],
                       descripcion: "vistas previas inteligentes de Lightroom Classic",
                       consecuencia: "Si tus fotos originales están en un disco desconectado, ya no podrás editarlas hasta conectarlo. Lightroom puede volver a crearlas (Biblioteca › Vistas previas). Tus fotos y ediciones no se tocan.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "* Previews.lrdata", marcadores: ["*.lrcat"],
                       descripcion: "vistas previas de Lightroom Classic",
                       consecuencia: "Lightroom las vuelve a crear al navegar por tus fotos (al principio irá más lento). Si tus originales están en un disco desconectado, verás las fotos en gris hasta que lo conectes. Tus fotos y ediciones no se tocan.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "Cache", marcadores: ["*.cocatalogdb"],
                       descripcion: "caché de un catálogo de Capture One",
                       consecuencia: "Capture One vuelve a crear miniaturas y vistas previas al navegar (tarda en catálogos grandes). Si tus originales están en un disco desconectado, no los verás hasta conectarlo. Tus fotos y ajustes no se tocan.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "blendcache_*", marcadores: ["*.blend"],
                       descripcion: "simulaciones horneadas de Blender",
                       consecuencia: "Tendrás que volver a hornear (bake) las simulaciones de física, humo o partículas; puede tardar horas y, si cambiaste la escena, el resultado puede no ser igual. Tu archivo .blend no se toca.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: ".utmp", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "temporales de Unity",
                       consecuencia: "Unity los vuelve a crear."),
        ReglaArtefacto(carpeta: "MemoryCaptures", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "capturas del Memory Profiler de Unity",
                       consecuencia: "Se pierden las capturas de memoria que guardaste para analizar. El proyecto no se toca.",
                       riesgo: .revisar),
        ReglaArtefacto(carpeta: "Recordings", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "grabaciones de Unity Recorder",
                       consecuencia: "Se pierden los vídeos e imágenes que grabaste con Unity Recorder y no se pueden regenerar solos: revisa antes lo que quieras conservar. El proyecto no se toca.",
                       riesgo: .revisar, soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "Build", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "compilaciones del juego (Unity)",
                       consecuencia: "Se pierden los juegos ya compilados y los proyectos de Xcode o Android Studio exportados (con los cambios que les hayas hecho a mano). Vuelve a generarlos con File › Build; si es una versión publicada, cópiala antes.",
                       riesgo: .revisar, soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "Builds", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "compilaciones del juego (Unity)",
                       consecuencia: "Se pierden los juegos ya compilados y los proyectos de Xcode o Android Studio exportados (con los cambios que les hayas hecho a mano). Vuelve a generarlos con File › Build; si es una versión publicada, cópiala antes.",
                       riesgo: .revisar, soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: "ServerData", marcadores: ["ProjectSettings/ProjectVersion.txt"],
                       descripcion: "contenido remoto de Addressables (Unity)",
                       consecuencia: "Se vuelve a generar al compilar los Addressables. Si lo subes a un servidor, súbelo de nuevo después.",
                       riesgo: .revisar, soloSiIgnoradaPorGit: true),
        ReglaArtefacto(carpeta: ".mono", marcadores: ["project.godot"],
                       descripcion: "compilación de C# de Godot 3",
                       consecuencia: "Godot la vuelve a generar al compilar el proyecto."),
        ReglaArtefacto(carpeta: ".internal", marcadores: ["game.project"],
                       descripcion: "caché del editor de Defold",
                       consecuencia: "Defold la vuelve a crear al abrir el proyecto."),
        ReglaArtefacto(carpeta: "build", marcadores: ["game.project"],
                       descripcion: "compilación de Defold",
                       consecuencia: "Defold la vuelve a generar al compilar."),
    ]
}
